version: "3"

volumes:
  dbdata:

services:
  mysqldb:
    image: mysql
    environment:
      - MYSQL_DB=users              
      - MYSQL_USER=root
      - MYSQL_PASSWORD=Parola123!
    volumes:
      - dbdata:/var/lib/mysql/data
  backend:
    build:
      context: ./
    environment:      
      - MYSQL_DB=users              
      - MYSQL_USER=root
      - MYSQL_PASSWORD=Parola123!
      - MYSQL_ROOT_PASSWORD=Parola123!
    ports:
      - "9966:9966"
    depends_on:
      - mysqldb
  frontend:
    build: 
      context: ./front-end
    ports:
      - "8088:8088"
    depends_on:
      - backend